version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
       - ./backend:/app/backend
       - /app/backend/node_modules
  frontend:
    build: ./
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
       - .:/app
       - /app/node_modules
    stdin_open: true
    tty: true